// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Envelope struct {
	MessageId            int32    `protobuf:"varint,1,opt,name=messageId,proto3" json:"messageId,omitempty"`
	Message              []byte   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Envelope) Reset()         { *m = Envelope{} }
func (m *Envelope) String() string { return proto.CompactTextString(m) }
func (*Envelope) ProtoMessage()    {}
func (*Envelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Envelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Envelope.Unmarshal(m, b)
}
func (m *Envelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Envelope.Marshal(b, m, deterministic)
}
func (m *Envelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Envelope.Merge(m, src)
}
func (m *Envelope) XXX_Size() int {
	return xxx_messageInfo_Envelope.Size(m)
}
func (m *Envelope) XXX_DiscardUnknown() {
	xxx_messageInfo_Envelope.DiscardUnknown(m)
}

var xxx_messageInfo_Envelope proto.InternalMessageInfo

func (m *Envelope) GetMessageId() int32 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

func (m *Envelope) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

// bot periodically knocks to the server
// msgId = 15
type Knock struct {
	BotId                string   `protobuf:"bytes,1,opt,name=botId,proto3" json:"botId,omitempty"`
	KnockId              uint32   `protobuf:"varint,2,opt,name=knockId,proto3" json:"knockId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Knock) Reset()         { *m = Knock{} }
func (m *Knock) String() string { return proto.CompactTextString(m) }
func (*Knock) ProtoMessage()    {}
func (*Knock) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *Knock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Knock.Unmarshal(m, b)
}
func (m *Knock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Knock.Marshal(b, m, deterministic)
}
func (m *Knock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Knock.Merge(m, src)
}
func (m *Knock) XXX_Size() int {
	return xxx_messageInfo_Knock.Size(m)
}
func (m *Knock) XXX_DiscardUnknown() {
	xxx_messageInfo_Knock.DiscardUnknown(m)
}

var xxx_messageInfo_Knock proto.InternalMessageInfo

func (m *Knock) GetBotId() string {
	if m != nil {
		return m.BotId
	}
	return ""
}

func (m *Knock) GetKnockId() uint32 {
	if m != nil {
		return m.KnockId
	}
	return 0
}

// Server always responds with task, but it may be empty
// in the demo, it will be simple -- launch cmd command
// msgId = 16
type Task struct {
	TaskId               uint32   `protobuf:"varint,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	Task                 string   `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetTaskId() uint32 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *Task) GetTask() string {
	if m != nil {
		return m.Task
	}
	return ""
}

// Task Response is recieved instead of knock
type TaskResponse struct {
	BotId                string   `protobuf:"bytes,1,opt,name=botId,proto3" json:"botId,omitempty"`
	KnockId              uint32   `protobuf:"varint,2,opt,name=knockId,proto3" json:"knockId,omitempty"`
	TaskId               uint32   `protobuf:"varint,3,opt,name=taskId,proto3" json:"taskId,omitempty"`
	Task                 string   `protobuf:"bytes,4,opt,name=task,proto3" json:"task,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskResponse) Reset()         { *m = TaskResponse{} }
func (m *TaskResponse) String() string { return proto.CompactTextString(m) }
func (*TaskResponse) ProtoMessage()    {}
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *TaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskResponse.Unmarshal(m, b)
}
func (m *TaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskResponse.Marshal(b, m, deterministic)
}
func (m *TaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskResponse.Merge(m, src)
}
func (m *TaskResponse) XXX_Size() int {
	return xxx_messageInfo_TaskResponse.Size(m)
}
func (m *TaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TaskResponse proto.InternalMessageInfo

func (m *TaskResponse) GetBotId() string {
	if m != nil {
		return m.BotId
	}
	return ""
}

func (m *TaskResponse) GetKnockId() uint32 {
	if m != nil {
		return m.KnockId
	}
	return 0
}

func (m *TaskResponse) GetTaskId() uint32 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *TaskResponse) GetTask() string {
	if m != nil {
		return m.Task
	}
	return ""
}

func init() {
	proto.RegisterType((*Envelope)(nil), "message.Envelope")
	proto.RegisterType((*Knock)(nil), "message.Knock")
	proto.RegisterType((*Task)(nil), "message.Task")
	proto.RegisterType((*TaskResponse)(nil), "message.TaskResponse")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 183 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x9c, 0xb8,
	0x38, 0x5c, 0xf3, 0xca, 0x52, 0x73, 0xf2, 0x0b, 0x52, 0x85, 0x64, 0xb8, 0x38, 0xa1, 0xc2, 0x9e,
	0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x08, 0x01, 0x21, 0x09, 0x2e, 0x98, 0x26, 0x09,
	0x26, 0x05, 0x46, 0x0d, 0x9e, 0x20, 0xb8, 0x19, 0xe6, 0x5c, 0xac, 0xde, 0x79, 0xf9, 0xc9, 0xd9,
	0x42, 0x22, 0x5c, 0xac, 0x49, 0xf9, 0x25, 0x50, 0xcd, 0x9c, 0x41, 0x10, 0x0e, 0x48, 0x63, 0x36,
	0x48, 0xda, 0x33, 0x05, 0xac, 0x91, 0x37, 0x08, 0xc6, 0x55, 0x32, 0xe2, 0x62, 0x09, 0x49, 0x2c,
	0xce, 0x16, 0x12, 0xe3, 0x62, 0x2b, 0x49, 0x2c, 0xce, 0x86, 0x6a, 0xe4, 0x0d, 0x82, 0xf2, 0x84,
	0x84, 0xb8, 0x58, 0x40, 0x2c, 0xb0, 0x36, 0xce, 0x20, 0x30, 0x5b, 0x29, 0x8b, 0x8b, 0x07, 0xa4,
	0x27, 0x28, 0xb5, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x95, 0x54, 0x3b, 0x91, 0xec, 0x62, 0xc6, 0x6a,
	0x17, 0x0b, 0xc2, 0xae, 0x24, 0x36, 0x70, 0x60, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x3a,
	0x40, 0x40, 0xe2, 0x3d, 0x01, 0x00, 0x00,
}
